#How you want your bot to be called. Usually something like "!"
COMMAND_PREFIX=

#Bot's name. Bot commands will be invoked with <COMMAND_PREFIX><BOT_NAME>, eg. "!polly". This is not case sensitive.
BOT_NAME="Polly"

#Discord bot key. Get this by registering a bot on the Discord developers page
BOT_KEY=

#Tenor API key. Necessary for meme commands, but the bot will do without if need be. See here: https://tenor.com/gifapi/documentation#quickstart
TENOR_KEY=""